version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  ignore:
  - dependency-name: async-trait
    versions:
    - 0.1.48
    - 0.1.49
  - dependency-name: sqlx
    versions:
    - 0.5.1
- package-ecosystem: docker
  directories:
    - "*"
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  ignore:
    - dependency-name: "*"
      update-types:
        - "version-update:semver-major"
