[workspace]
members = [
    ".",
    "esrs-core",
    "examples/postgres"
]

[package]
name = "esrs"
version = "0.3.0"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"
description = "A Prima.it-opinionated library to achieve cqrs/es"
repository = "https://github.com/primait/event_sourcing.rs"
keywords = ["event_sourcing", "async", "postgres"]
categories = ["event_sourcing"]
authors = ["Simone Cottini <cottini.simone@gmail.com>"]

[dependencies]
esrs-core = { version = "0.3.0", path = "esrs-core", default-features = false }

[dev-dependencies]
postgres-example = { path = "examples/postgres" }
actix-rt = "^1.0"

[features]
postgres = []
