[package]
name = "esrs"
version = "0.2.1"
authors = ["Simone Cottini <cottini.simone@gmail.com>"]
edition = "2018"
description = "A Prima.it-opinionated library to achieve cqrs/es"
license = "MIT"
repository = "https://github.com/primait/event_sourcing.rs"

[features]
blocking = []
async = ["sqlx", "async-std"]
postgresql = []

[dependencies]
# Serialization/Deserialization
serde = {version = "^1.0", features = ["derive"]}
serde_json = "^1.0"
# Uuid generation
uuid = {version = "^0.8.1", features = ["serde", "v4"]}
# Time lib
chrono = {version = "^0.4", features = ["serde"]}
# Build async trait
async-trait = "0.1.40"

# Sql library for async impl
sqlx = { version = "0.4.1", features = [ "postgres", "runtime-async-std-native-tls", "uuid", "json", "chrono" ], optional = true }
async-std = { version = "1.6", features = [ "attributes" ], optional = true }
