#!/usr/bin/env bash

export DATABASE_URL="postgresql://postgres:postgres@postgres:5432/postgres"
export RABBIT_URL="amqp://rabbit:rabbit@rabbit/rabbit"
export KAFKA_BROKERS_URL="kafka:9092"

sh -c "$@"