[tasks.build-ci]
description = "Build Lira inside CI."
command = "cargo"
args = ["build", "-j", "2", "--all-features"]

[tasks.format-ci]
description = "Runs the cargo rustfmt plugin during CI."
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.test]
description = "Run tests."
command = "cargo"
args = ["test", "${@}", "--all-features"]

[tasks.clippy-ci]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]
