[env]
DATABASE_URL = "postgresql://postgres:postgres@localhost:5432/postgres"

[env.drone]
DATABASE_URL = "postgresql://postgres:postgres@postgres:5432/postgres"

[config]
default_to_workspace = false

# Check
[tasks.check]
description = "Run checks for each feature"
dependencies = ["check-ci"]

[tasks.check-ci]
script = [
    "cargo check --workspace",
    "cargo check --workspace --features=postgres",
    "cargo check --workspace --features=kafka",
    "cargo check --workspace --features=rabbit",
    "cargo check --workspace --all-features"
]

# Build
[tasks.build-ci]
script = [
    "cargo build -j 2 --workspace",
    "cargo build -j 2 --workspace --features=postgres",
    "cargo build -j 2 --workspace --features=kafka",
    "cargo build -j 2 --workspace --features=rabbit",
    "cargo build -j 2 --workspace --all-features"
]

# Format
[tasks.format-ci]
description = "Runs the cargo rustfmt plugin during CI."
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

# Tests
[tasks.test]
description = "Run tests."
dependencies = ["test-ci"]

[tasks.test-ci]
script = [
    "cargo test ${@} --workspace",
    "cargo test ${@} --workspace --features=postgres",
    "cargo test ${@} --workspace --features=kafka",
    "cargo test ${@} --workspace --features=rabbit",
    "cargo test ${@} --workspace --all-features"
]

# Clippy
[tasks.clippy-ci]
description = "Run clippy linter."
script = [
    "cargo clippy --workspace -- -D warnings",
    "cargo clippy --workspace --features=postgres -- -D warnings",
    "cargo clippy --workspace --features=kafka -- -D warnings",
    "cargo clippy --workspace --features=rabbit -- -D warnings",
    "cargo clippy --workspace --all-features -- -D warnings"
]

# Run example
[tasks.example]
description = "Run given example."
command = "cargo"
args = ["run", "-p", "${@}"]

# Docs
[tasks.docsrs]
description = "Build docs as they are rendered on docs.rs"
command = "cargo"
args = ["doc", "--all-features"]

[tasks.cargo-prune]
description = "Run cargo prune"
command = "cargo"
args = ["prune"]

[tasks.print-stats]
description = "Print cache size"
command = "du"
args = ["-sh", "target", ".cargo"]

[tasks.cache-cleanup]
description = "Clean CI cache"
dependencies = ["cargo-prune", "delete-artifacts", "print-stats"]

[tasks.delete-artifacts]
description = "Remove non cachable artifacts"
script = [
    '''
    #!/bin/bash
    set -e
    set -x
    find ./target/debug -type f -maxdepth 1 -delete || true
    rm -rf ./target/{debug,release}/deps/{*prima-tracing*}
    rm -rf ./target/{debug,release}/.fingerprint/*prima-tracing*
    ''',
]
