name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: install cargo-make
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-make
      - name: Build
        run: cargo make build

  lint:
    # Avoid duplicate jobs on PR from a branch on the same repo
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: install cargo-make
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-make
      - name: cargo fmt
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo make clippy
      - name: Build docs
        run: cargo doc --document-private-items --all-features --no-deps
    env:
      RUSTDOCFLAGS: -Dwarnings

  test:
    # Avoid duplicate jobs on PR from a branch on the same repo
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: install cargo-make
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-make
      - name: Add hosts entries
        run: |
          echo "
          127.0.0.1 postgres
          127.0.0.1 kafka
          127.0.0.1 rabbit
          " | sudo tee /etc/hosts
      - name: Run tests
        run: cargo make test
    services:
      postgres:
        image: public.ecr.aws/bitnami/postgresql:16
        ports:
          - 5432:5432
        env:
          POSTGRESQL_DATABASE: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres

  alls-green:
    # I hate github actions.
    # A default status check of success() is applied unless you include another status check function, like always().
    # https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions
    # https://stackoverflow.com/questions/58858429/how-to-run-a-github-actions-step-even-if-the-previous-step-fails-while-still-f

    if: always() && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name)
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
